// Sample resume data for template previews
export const sampleResumeData = {
  personalInfo: {
    firstName: 'Abubakar',
    lastName: '',
    title: 'Vice President, Health Policy and Regulatory Affairs',
    email: 'abubaker@email.com',
    phone: '323.677.058',
    location: 'Washington, District of Columbia',
    linkedIn: 'LinkedIn',
  },
  summary: 'Senior leader with 20+ years of experience driving revenue growth and operational excellence in healthcare services. Expertise in securing strategic partnerships, managing complex sales cycles, and expanding market footprint across the Northeast region. Proven ability to lead cross-functional teams, optimize patient care transitions, and build lasting relationships with key stakeholders. Skilled in KPI tracking, process improvement, and executing growth strategies to ensure sustainable success in post-acute and home health sectors.',
  skills: [
    { id: '1', name: 'Business Development', level: 'Expert' as const },
    { id: '2', name: 'Revenue Growth', level: 'Expert' as const },
    { id: '3', name: 'Strategic Planning', level: 'Expert' as const },
    { id: '4', name: 'Partnership Development', level: 'Expert' as const },
    { id: '5', name: 'Sales Leadership', level: 'Expert' as const },
    { id: '6', name: 'Negotiation Skills', level: 'Expert' as const },
    { id: '7', name: 'Stakeholder Management', level: 'Expert' as const },
    { id: '8', name: 'Client Relationship Building', level: 'Expert' as const },
    { id: '9', name: 'Healthcare Industry Knowledge', level: 'Expert' as const },
    { id: '10', name: 'Post-Acute Care Expertise', level: 'Expert' as const },
    { id: '11', name: 'Patient Retention Strategies', level: 'Expert' as const },
    { id: '12', name: 'Operational Excellence', level: 'Expert' as const },
    { id: '13', name: 'Cross-Functional Leadership', level: 'Expert' as const },
    { id: '14', name: 'KPI Tracking', level: 'Expert' as const },
    { id: '15', name: 'CRM Systems Proficiency', level: 'Expert' as const },
    { id: '16', name: 'Process Improvement (Six Sigma, Lean)', level: 'Expert' as const },
    { id: '17', name: 'Team Collaboration', level: 'Expert' as const },
    { id: '18', name: 'Healthcare Referral Networks', level: 'Expert' as const },
    { id: '19', name: 'Transition Management', level: 'Expert' as const },
    { id: '20', name: 'Emotional Intelligence', level: 'Expert' as const },
  ],
  experience: [
    {
      id: '1',
      company: 'HealthSour',
      position: 'Vice President, Health Policy and Regulatory Affairs',
      startDate: '2018',
      endDate: 'Present',
      current: true,
      description: '',
      achievements: [
        'Led and supervised a dedicated team focused on regulatory, quality, policy analysis, and legislative affairs for nursing homes, skilled nursing facilities, life plan communities, and related settings.',
        'Collaborated with senior leadership within the Policy Department to ensure coordinated strategies, maximizing effectiveness in Public Policy & Advocacy efforts.',
        'Developed and executed a robust education program for members, covering national emerging policies, trends, and the legislative landscape affecting nursing homes and life plan communities.',
        'Represented LeadingAge in front of federal policymakers, Capitol Hill, media, and other associations, advancing the organization\'s policy goals and ensuring a strong presence in relevant policy discussions.',
      ],
    },
    {
      id: '2',
      company: 'LeadingAge',
      position: 'Director, Health Regulation and Policy',
      startDate: '2013',
      endDate: '2018',
      current: false,
      description: '',
      achievements: [
        'Led the development and implementation of health regulation and policy strategies for a national nonprofit organization focused on aging services.',
        'Managed federal and state-level policy advocacy efforts, influencing health regulation changes that impacted long-term care and senior services.',
        'Conducted in-depth policy analysis to support the organization\'s mission and provide actionable recommendations to leadership and stakeholders.',
        'Worked with government agencies, industry leaders, and policymakers to shape regulations and ensure compliance with healthcare standards in aging services.',
      ],
    },
  ],
  education: [
    {
      id: '1',
      institution: 'Cleveland State University',
      degree: 'Masters of Business Administration (M.B.A.)',
      field: 'Business Administration',
      startDate: '',
      endDate: '',
    },
    {
      id: '2',
      institution: 'Stonehill College',
      degree: 'Bachelor of Science in Biology',
      field: 'Biology',
      startDate: '',
      endDate: '2004',
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'Certified Healthcare Executive (CHE)',
      issuer: 'American College of Healthcare Executives',
      date: '',
    },
    {
      id: '2',
      name: 'Lean Six Sigma Black Belt',
      issuer: 'Institute of Industrial Engineers',
      date: '',
    },
    {
      id: '3',
      name: 'Healthcare Policy Certification',
      issuer: 'Harvard Kennedy School Executive Education',
      date: '',
    },
  ],
  affiliations: [
    'Member, American Public Health Association (APHA)',
    'Board Member, National Association for Home Care & Hospice',
    'Fellow, American College of Healthcare Executives (FACHE)',
  ],
}

export default sampleResumeData
